"""ogun kaydi ogrenme sinyalleri

Revision ID: 7d2827aa70db
Revises: a4c43e0c439c
Create Date: 2026-08-11 15:46:05.890951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2827aa70db'
down_revision: Union[str, Sequence[str], None] = 'a4c43e0c439c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('local_hour', sa.Integer(), nullable=True))
    batch_op.create_check_constraint(
            "local_hour_range", "local_hour IS NULL OR (local_hour BETWEEN 0 AND 23)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_constraint("local_hour_range", type_="check")
        batch_op.drop_column('local_hour')
        batch_op.drop_column('ingredients_json')

    # ### end Alembic commands ###
