"""ilk sema 22 tablo

Revision ID: a5f119801c2a
Revises: 
Create Date: 2026-08-04 15:10:06.096483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f119801c2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allergens')),
    sa.UniqueConstraint('code', name=op.f('uq_allergens_code'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code'))
    )
    op.create_table('diet_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_tags')),
    sa.UniqueConstraint('code', name=op.f('uq_diet_tags_code'))
    )
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_cache'))
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index('ix_cache_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_cache_cache_key'), ['cache_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversations'))
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conv_user_last', ['user_id', 'last_message_at'], unique=False)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('default_unit_type', sa.Enum('mass', 'volume', 'count', name='unittype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('default_unit', sa.Enum('g', 'kg', 'ml', 'l', 'adet', 'paket', 'yemek_kasigi', 'tatli_kasigi', 'cay_kasigi', 'su_bardagi', 'demet', 'dilim', name='unitcode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('grams_per_piece', sa.Float(), nullable=True),
    sa.Column('ml_to_gram_factor', sa.Float(), nullable=True),
    sa.Column('cooked_yield_factor', sa.Float(), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_per_100g', sa.Float(), nullable=True),
    sa.Column('carb_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_per_100g', sa.Float(), nullable=True),
    sa.Column('fiber_per_100g', sa.Float(), nullable=True),
    sa.Column('sugar_per_100g', sa.Float(), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Float(), nullable=True),
    sa.Column('avg_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('season_months', sa.String(length=30), nullable=True),
    sa.Column('avg_price_per_100g', sa.Float(), nullable=True),
    sa.Column('is_staple', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_ingredients_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_canonical_name'), ['canonical_name'], unique=True)
        batch_op.create_index('ix_ingredients_category', ['category_id'], unique=False)

    op.create_table('recipe_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipe_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_favorites')),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_favorite_user_recipe')
    )
    op.create_table('recipe_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.String(length=24), nullable=False),
    sa.Column('action', sa.Enum('begendim', 'begenmedim', 'yaptim', 'atladim', name='feedbackaction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('servings_cooked', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 1 AND 5)', name=op.f('ck_recipe_feedback_rating_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipe_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_feedback'))
    )
    with op.batch_alter_table('recipe_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_user_recipe', ['user_id', 'recipe_id'], unique=False)
        batch_op.create_index('ix_feedback_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('user_allergens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], name=op.f('fk_user_allergens_allergen_id_allergens'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_allergens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'allergen_id', name=op.f('pk_user_allergens'))
    )
    op.create_table('user_diet_tags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diet_tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['diet_tag_id'], ['diet_tags.id'], name=op.f('fk_user_diet_tags_diet_tag_id_diet_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_diet_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'diet_tag_id', name=op.f('pk_user_diet_tags'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('erkek', 'kadin', 'belirtilmedi', name='gender', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedanter', 'hafif', 'orta', 'yuksek', 'cok_yuksek', name='activitylevel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('goal', sa.Enum('kilo_verme', 'koruma', 'kilo_alma', name='goal', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('tdee', sa.Float(), nullable=True),
    sa.Column('daily_calorie_target', sa.Float(), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=True),
    sa.Column('carb_target_g', sa.Float(), nullable=True),
    sa.Column('fat_target_g', sa.Float(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('user_taste_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('cuisine', 'diet_tag', 'ingredient', 'difficulty', name='tastedimension', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('taste_key', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('weight BETWEEN -1 AND 1', name=op.f('ck_user_taste_weights_weight_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_taste_weights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_taste_weights')),
    sa.UniqueConstraint('user_id', 'dimension', 'taste_key', name='uq_taste_user_dim_key')
    )
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weight_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_logs')),
    sa.UniqueConstraint('user_id', 'logged_date', name='uq_weight_user_date')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('suggested_recipe_ids', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('fk_chat_messages_conversation_id_chat_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_msg_conv_time', ['conversation_id', 'created_at'], unique=False)

    op.create_table('ingredient_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_ingredient_aliases_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_aliases'))
    )
    with op.batch_alter_table('ingredient_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_alias_ingredient', ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_aliases_alias'), ['alias'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('package_quantity', sa.Float(), nullable=True),
    sa.Column('package_unit', sa.Enum('g', 'kg', 'ml', 'l', 'adet', 'paket', 'yemek_kasigi', 'tatli_kasigi', 'cay_kasigi', 'su_bardagi', 'demet', 'dilim', name='unitcode', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('serving_size_g', sa.Float(), nullable=True),
    sa.Column('serving_description', sa.String(length=100), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_per_100g', sa.Float(), nullable=True),
    sa.Column('carb_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_per_100g', sa.Float(), nullable=True),
    sa.Column('fiber_per_100g', sa.Float(), nullable=True),
    sa.Column('sugar_per_100g', sa.Float(), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('openfoodfacts', 'user', 'admin', name='productsource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_products_ingredient_id_ingredients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index('ix_products_ingredient', ['ingredient_id'], unique=False)
        batch_op.create_index('ix_products_name', ['name'], unique=False)

    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Enum('g', 'kg', 'ml', 'l', 'adet', 'paket', 'yemek_kasigi', 'tatli_kasigi', 'cay_kasigi', 'su_bardagi', 'demet', 'dilim', name='unitcode', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('source', sa.Enum('manuel', 'esik', 'tarif', 'ongoru', name='shoppingsource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_recipe_id', sa.String(length=24), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('item_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_shopping_list_items_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_list_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items')),
    sa.UniqueConstraint('user_id', 'ingredient_id', name='uq_shopping_user_ingredient')
    )
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.create_index('ix_shopping_user_checked', ['user_id', 'is_checked'], unique=False)

    op.create_table('unmatched_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=255), nullable=False),
    sa.Column('normalized_text', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('resolved_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_ingredient_id'], ['ingredients.id'], name=op.f('fk_unmatched_ingredients_resolved_ingredient_id_ingredients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unmatched_ingredients'))
    )
    with op.batch_alter_table('unmatched_ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_unmatched_count', ['occurrence_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_unmatched_ingredients_normalized_text'), ['normalized_text'], unique=True)
        batch_op.create_index('ix_unmatched_resolved', ['resolved_ingredient_id'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('kahvalti', 'ogle', 'aksam', 'atistirma', name='mealtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('manuel', 'barkod', 'tarif', name='logsource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.String(length=24), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carb_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_meal_logs_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_meal_logs_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_logs'))
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index('ix_meals_user_date', ['user_id', 'logged_date'], unique=False)
        batch_op.create_index('ix_meals_user_date_type', ['user_id', 'logged_date', 'meal_type'], unique=False)

    op.create_table('pantry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=150), nullable=True),
    sa.Column('quantity_base', sa.Float(), nullable=False),
    sa.Column('unit_type', sa.Enum('mass', 'volume', 'count', name='unittype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('display_unit', sa.Enum('g', 'kg', 'ml', 'l', 'adet', 'paket', 'yemek_kasigi', 'tatli_kasigi', 'cay_kasigi', 'su_bardagi', 'demet', 'dilim', name='unitcode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('min_threshold_base', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_restocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_base >= 0', name=op.f('ck_pantry_items_quantity_nonnegative')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_pantry_items_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_pantry_items_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pantry_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_items')),
    sa.UniqueConstraint('user_id', 'ingredient_id', name='uq_pantry_user_ingredient')
    )
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.create_index('ix_pantry_expiry', ['expiry_date'], unique=False)
        batch_op.create_index('ix_pantry_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('pantry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('pantry_item_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('eklendi', 'arttirildi', 'tuketildi_tarif', 'tuketildi_manuel', 'bozuldu_atildi', 'duzeltme', 'silindi', name='pantryeventtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity_base_delta', sa.Float(), nullable=False),
    sa.Column('unit_type', sa.Enum('mass', 'volume', 'count', name='unittype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('recipe_id', sa.String(length=24), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('event_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_pantry_events_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantry_items.id'], name=op.f('fk_pantry_events_pantry_item_id_pantry_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pantry_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_events'))
    )
    with op.batch_alter_table('pantry_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_user_ing_time', ['user_id', 'ingredient_id', 'created_at'], unique=False)
        batch_op.create_index('ix_events_user_time', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_events_user_type', ['user_id', 'event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_user_type')
        batch_op.drop_index('ix_events_user_time')
        batch_op.drop_index('ix_events_user_ing_time')

    op.drop_table('pantry_events')
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.drop_index('ix_pantry_user_active')
        batch_op.drop_index('ix_pantry_expiry')

    op.drop_table('pantry_items')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_meals_user_date_type')
        batch_op.drop_index('ix_meals_user_date')

    op.drop_table('meal_logs')
    with op.batch_alter_table('unmatched_ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_unmatched_resolved')
        batch_op.drop_index(batch_op.f('ix_unmatched_ingredients_normalized_text'))
        batch_op.drop_index('ix_unmatched_count')

    op.drop_table('unmatched_ingredients')
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_user_checked')

    op.drop_table('shopping_list_items')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_name')
        batch_op.drop_index('ix_products_ingredient')
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('ingredient_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_aliases_alias'))
        batch_op.drop_index('ix_alias_ingredient')

    op.drop_table('ingredient_aliases')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_msg_conv_time')

    op.drop_table('chat_messages')
    op.drop_table('weight_logs')
    op.drop_table('user_taste_weights')
    op.drop_table('user_profiles')
    op.drop_table('user_diet_tags')
    op.drop_table('user_allergens')
    with op.batch_alter_table('recipe_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_user_time')
        batch_op.drop_index('ix_feedback_user_recipe')

    op.drop_table('recipe_feedback')
    op.drop_table('recipe_favorites')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_category')
        batch_op.drop_index(batch_op.f('ix_ingredients_canonical_name'))

    op.drop_table('ingredients')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conv_user_last')

    op.drop_table('chat_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cache_cache_key'))
        batch_op.drop_index('ix_cache_expires')

    op.drop_table('llm_cache')
    op.drop_table('diet_tags')
    op.drop_table('categories')
    op.drop_table('allergens')
    # ### end Alembic commands ###
