"""w4-t13 performans indeksleri

Revision ID: 48f94dc8f641
Revises: baa04227f707
Create Date: 2026-08-26 11:53:20.709646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f94dc8f641'
down_revision: Union[str, Sequence[str], None] = 'baa04227f707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.create_index('ix_pantry_user_updated', ['user_id', 'updated_at'], unique=False)

    with op.batch_alter_table('recipe_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_user_action_time', ['user_id', 'action', 'created_at'], unique=False)

    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.create_index('ix_shopping_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_user_created')

    with op.batch_alter_table('recipe_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_user_action_time')

    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.drop_index('ix_pantry_user_updated')

    # ### end Alembic commands ###
