"""swipe oturumlari ve geri bildirim sebepleri

Revision ID: a4c43e0c439c
Revises: f7a3a08b9ed7
Create Date: 2026-08-11 14:15:06.250638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c43e0c439c'
down_revision: Union[str, Sequence[str], None] = 'f7a3a08b9ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

action_type = sa.Enum(
    "gordu", "begendim", "begenmedim", "yapacagim", "kaydetti", "yaptim",
    name="feedbackaction", native_enum=False, create_constraint=True,
)
reason_type = sa.Enum(
    "sevmedim", "cok_uzun", "malzeme_yok",
    name="feedbackreason", native_enum=False, create_constraint=True,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'swipe_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), 
                  nullable=False),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('filters_json', sa.Text(), nullable=True),
        sa.Column('shown_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], 
                                name=op.f('fk_swipe_sessions_user_id_users'), 
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_swipe_sessions'))
    )
    op.create_index("ix_swipe_user_started", "swipe_sessions", ["user_id", "started_at"])
    op.drop_table("recipe_feedback")

    op.create_table(
        "recipe_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.String(length=24), nullable=False),
        sa.Column("action", action_type, nullable=False),
        sa.Column("reason", reason_type, nullable=True),
        sa.Column("missing_ingredient_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("servings_cooked", sa.Float(), nullable=True),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"),
                  nullable=False),
        sa.CheckConstraint("rating IS NULL OR (rating BETWEEN 1 AND 5)",
                           name=op.f("ck_recipe_feedback_rating_range")),
        sa.CheckConstraint("reason IS NULL OR action = 'begenmedim'",
                           name=op.f("ck_recipe_feedback_reason_only_on_dislike")),
        sa.CheckConstraint("missing_ingredient_id IS NULL OR reason = 'malzeme_yok'",
                           name=op.f("ck_recipe_feedback_missing_needs_reason")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],
                                name=op.f("fk_recipe_feedback_user_id_users"),
                                ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["missing_ingredient_id"], ["ingredients.id"],
    name=op.f("fk_recipe_feedback_missing_ingredient_id_ingredients"), ondelete= "SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["swipe_sessions.id"],
                                name=op.f("fk_recipe_feedback_session_id_swipe_sessions"),
                                ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_feedback")),
    )

    op.create_index("ix_feedback_user_recipe", "recipe_feedback", ["user_id", "recipe_id"])
    op.create_index("ix_feedback_session", "recipe_feedback", ["session_id", "recipe_id"])
    op.create_index("ix_feedback_user_reason_time", "recipe_feedback",
                    ["user_id", "reason", "created_at"])

    # with op.batch_alter_table('swipe_sessions', schema=None) as batch_op:
    #     batch_op.create_index('ix_swipe_user_started', ['user_id', 'started_at'], unique=False)

    # with op.batch_alter_table('recipe_feedback', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('missing_ingredient_id', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('reason', sa.Enum('sevmedim', 'cok_uzun', 'malzeme_yok', name='feedbackreason', native_enum=False, create_constraint=True), nullable=True))
    #     batch_op.drop_index(batch_op.f('ix_feedback_user_time'))
    #     batch_op.create_index('ix_feedback_session', ['session_id', 'recipe_id'], unique=False)
    #     batch_op.create_index('ix_feedback_user_reason_time', ['user_id', 'reason', 'created_at'], unique=False)
    #     batch_op.create_foreign_key(batch_op.f('fk_recipe_feedback_missing_ingredient_id_ingredients'), 'ingredients', ['missing_ingredient_id'], ['id'], ondelete='SET NULL')
    #     batch_op.create_foreign_key(batch_op.f('fk_recipe_feedback_session_id_swipe_sessions'), 'swipe_sessions', ['session_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_feedback_user_reason_time", table_name="recipe_feedback")
    op.drop_index("ix_feedback_session", table_name="recipe_feedback")
    op.drop_index("ix_feedback_user_recipe", table_name="recipe_feedback")
    op.drop_table("recipe_feedback")

    eski_action = sa.Enum(
        "begendim", "begenmedim", "yaptim", "atladim",
        name="feedbackaction", native_enum=False, create_constraint=True,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.String(length=24), nullable=False),
        sa.Column("action", eski_action, nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("servings_cooked", sa.Float(), nullable=True),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"),
                  nullable=False),
        sa.CheckConstraint("rating IS NULL OR (rating BETWEEN 1 AND 5)",
                           name=op.f("ck_recipe_feedback_rating_range")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],
                                name=op.f("fk_recipe_feedback_user_id_users"),
                                ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_feedback")),
    )
    op.create_index("ix_feedback_user_recipe", "recipe_feedback", ["user_id", "recipe_id"])
    op.create_index("ix_feedback_user_time", "recipe_feedback", ["user_id", "created_at"])

    op.drop_index("ix_swipe_user_started", table_name="swipe_sessions")
    op.drop_table("swipe_sessions")
    # with op.batch_alter_table('recipe_feedback', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('fk_recipe_feedback_session_id_swipe_sessions'), type_='foreignkey')
    #     batch_op.drop_constraint(batch_op.f('fk_recipe_feedback_missing_ingredient_id_ingredients'), type_='foreignkey')
    #     batch_op.drop_index('ix_feedback_user_reason_time')
    #     batch_op.drop_index('ix_feedback_session')
    #     batch_op.create_index(batch_op.f('ix_feedback_user_time'), ['user_id', 'created_at'], unique=False)
    #     batch_op.drop_column('reason')
    #     batch_op.drop_column('missing_ingredient_id')
    #     batch_op.drop_column('session_id')

    # with op.batch_alter_table('swipe_sessions', schema=None) as batch_op:
    #     batch_op.drop_index('ix_swipe_user_started')

    # op.drop_table('swipe_sessions')
    # ### end Alembic commands ###
