"""sohbet mesajlarina foto ve tespit alanlari

Revision ID: 98414fbf66a1
Revises: e0810a25a9fe
Create Date: 2026-08-13 15:25:11.730997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98414fbf66a1'
down_revision: Union[str, Sequence[str], None] = 'e0810a25a9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
