"""gorme istekleri tablosu

Revision ID: 572c61a71e9b
Revises: 7d2827aa70db
Create Date: 2026-08-11 16:07:51.239830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572c61a71e9b'
down_revision: Union[str, Sequence[str], None] = '7d2827aa70db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('malzeme', 'ogun', name='visionrequesttype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('image_bytes', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vision_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vision_requests'))
    )
    with op.batch_alter_table('vision_requests', schema=None) as batch_op:
        batch_op.create_index('ix_vision_image_hash', ['image_hash'], unique=False)
        batch_op.create_index('ix_vision_user_time', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vision_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_vision_user_time')
        batch_op.drop_index('ix_vision_image_hash')

    op.drop_table('vision_requests')
    # ### end Alembic commands ###
