"""sohbet mesajlarina foto ve tespit alanlari

Revision ID: e0810a25a9fe
Revises: 572c61a71e9b
Create Date: 2026-08-13 15:13:54.038274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0810a25a9fe'
down_revision: Union[str, Sequence[str], None] = '572c61a71e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('detected_ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('detected_ingredients')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
